name: Code Quality Check
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main # INFO: Used in the template
      - example/* # INFO: Used in the template
      - feature/*
  pull_request:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  code-quality-check:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint TypeScript
        run: pnpm lint:types

      - name: Lint ESLint
        run: pnpm lint:all

      - name: Test
        run: pnpm test:cov
